import type { Project } from "./types";

// Fixed timestamp so SSR and client first render produce identical markup.
// Real activity uses live timestamps.
const SEED_TS = "2026-05-31T00:00:00.000Z";
const now = () => SEED_TS;

export const SEED_PROJECTS: Project[] = [
  {
    id: "bot-card-studio",
    name: "Bot Card Studio",
    summary: "Trading-card style profile cards for every bot in the tree.",
    status: "Active",
    currentMode: "Mode 2 / Plan",
    currentBot: "Tinker",
    nextAction: "Tinker delivers v1 prototype URL",
    updatedAt: now(),
    clarity:
      "I want a printable + digital trading card per bot. Front: portrait, name, role, branch. Back: stats, strengths, weaknesses, a quote. Tone matches DaBotTree — warm, hand-drawn edges, lantern light.",
    shapeNotes:
      "- card size 2.5 x 3.5 in (poker)\n- front + back layout\n- 1 master template, themed by branch\n- export PNG + PDF sheet of 9",
    shapeBotOutput:
      "Echo: aligned with existing portrait library. Ledger: filed as BCS-001. Recommend Momma Bear to draft master prompt next.",
    shapeArtifact: "https://example.com/bcs/shape-notes",
    planNotes:
      "- Momma Bear master prompt → Tinker prototype → Luma review → Weaver package\n- target: 18 cards (one per active bot)\n- print test on matte cardstock",
    planBotOutput:
      "Momma Bear master prompt v1 complete. Tinker working on prototype. Estimated 2 working sessions to first proof.",
    planArtifact: "https://example.com/bcs/master-prompt",
    handoffs: [
      {
        id: "h1",
        step: 1,
        mode: "Mode 0 / Clarity Intake",
        bot: "Boss",
        assignment: "Write the plain-language ask. What is this, who is it for, what does done look like.",
        status: "Complete",
        artifactTitle: "Clarity brief",
        artifactBody:
          "Printable + digital trading cards for every bot. Warm DaBotTree feel. Set of ~18 to start.",
        completedAt: now(),
        nextBot: "Echo",
        nextStep: "Memory alignment",
      },
      {
        id: "h2",
        step: 2,
        mode: "Memory alignment",
        bot: "Echo",
        assignment: "Pull every existing bot portrait + role description. Flag missing.",
        status: "Complete",
        artifactTitle: "Echo alignment notes",
        artifactBody: "17 portraits located. Missing: Tally back-portrait. Recommend mid-shot pull.",
        completedAt: now(),
        nextBot: "Ledger",
        nextStep: "Official record",
      },
      {
        id: "h3",
        step: 3,
        mode: "Official record",
        bot: "Ledger",
        assignment: "Open project file BCS-001 with intake + scope.",
        status: "Complete",
        artifactTitle: "BCS-001 record",
        artifactLink: "https://example.com/ledger/BCS-001",
        completedAt: now(),
        nextBot: "Momma Bear",
        nextStep: "Master prompt",
      },
      {
        id: "h4",
        step: 4,
        mode: "Master prompt",
        bot: "Momma Bear",
        assignment: "Author the master generation prompt for card front + back.",
        status: "Complete",
        artifactTitle: "Master prompt v1",
        artifactBody:
          "PROMPT: A trading card portrait of {bot.name}, {bot.role}. Warm lantern light, hand-drawn border, branch color {bot.branchHue}. Back: stats panel...",
        completedAt: now(),
        nextBot: "Tinker",
        nextStep: "Prototype",
      },
      {
        id: "h5",
        step: 5,
        mode: "Prototype",
        bot: "Tinker",
        assignment: "Render 3 sample cards using master prompt. Return URL.",
        status: "Working",
        nextBot: "Luma",
        nextStep: "Design review",
      },
      {
        id: "h6",
        step: 6,
        mode: "Design review",
        bot: "Luma",
        assignment: "Review prototype for tone, balance, legibility. Mark up.",
        status: "Not Started",
        nextBot: "Weaver",
        nextStep: "Final package",
      },
      {
        id: "h7",
        step: 7,
        mode: "Final package",
        bot: "Weaver",
        assignment: "Bundle PNG set + PDF print sheet + asset manifest.",
        status: "Not Started",
      },
    ],
    artifacts: [
      {
        id: "a1",
        title: "Clarity brief",
        kind: "intake",
        body: "Trading cards for every bot. Warm DaBotTree feel.",
        bot: "Boss",
        createdAt: now(),
      },
      {
        id: "a2",
        title: "Master prompt v1",
        kind: "prompt",
        body: "PROMPT: A trading card portrait of {bot.name}...",
        bot: "Momma Bear",
        createdAt: now(),
      },
      {
        id: "a3",
        title: "BCS-001 record",
        kind: "ledger entry",
        link: "https://example.com/ledger/BCS-001",
        bot: "Ledger",
        createdAt: now(),
      },
    ],
    activity: [
      { id: "ev1", at: now(), bot: "Boss", action: "opened project", status: "Draft" },
      { id: "ev2", at: now(), bot: "Echo", action: "completed memory alignment", status: "Complete" },
      { id: "ev3", at: now(), bot: "Ledger", action: "filed BCS-001", status: "Complete" },
      { id: "ev4", at: now(), bot: "Momma Bear", action: "delivered master prompt v1", status: "Complete" },
      { id: "ev5", at: now(), bot: "Tinker", action: "started prototype render", status: "Working" },
    ],
  },
  {
    id: "debauchery",
    name: "Debauchery",
    summary: "After-hours playground — looser experiments behind the velvet curtain.",
    status: "Waiting",
    currentMode: "Mode 1 / Shape",
    currentBot: "Boss",
    nextAction: "Boss to finalize tone guardrails",
    updatedAt: now(),
    clarity: "A space for looser, riskier creative work that doesn't fit the canopy.",
    shapeNotes: "- velvet curtain motif\n- separate access gate\n- explicit content rules pending",
    shapeBotOutput: "",
    planNotes: "",
    planBotOutput: "",
    handoffs: [
      {
        id: "d1",
        step: 1,
        mode: "Mode 0 / Clarity Intake",
        bot: "Boss",
        assignment: "Draft scope + guardrails.",
        status: "Complete",
        completedAt: now(),
        nextBot: "Boss",
        nextStep: "Tone guardrails",
      },
      {
        id: "d2",
        step: 2,
        mode: "Tone guardrails",
        bot: "Boss",
        assignment: "Set the rules of the room.",
        status: "Working",
      },
    ],
    artifacts: [],
    activity: [
      { id: "dv1", at: now(), bot: "Boss", action: "opened project", status: "Draft" },
    ],
  },
  {
    id: "wr1-repair-system",
    name: "WR1 Repair System",
    summary: "Field-repair workflow for WR1 units — diagnostic → part swap → verify.",
    status: "Blocked",
    currentMode: "Mode 1 / Shape",
    currentBot: "Tinker",
    nextAction: "Resolve parts catalog access",
    blocker: "Awaiting parts catalog credentials from supplier.",
    updatedAt: now(),
    clarity:
      "We need a repeatable repair flow for WR1 units in the field. Tech opens app, runs diagnostic, swaps flagged part, verifies, files report.",
    shapeNotes: "- 5-step flow\n- offline-first\n- attach photos to report",
    shapeBotOutput: "Tinker: blocked on parts catalog API access.",
    planNotes: "",
    planBotOutput: "",
    handoffs: [
      {
        id: "w1",
        step: 1,
        mode: "Mode 0 / Clarity Intake",
        bot: "Boss",
        assignment: "Describe the field repair pain.",
        status: "Complete",
        completedAt: now(),
        nextBot: "Tinker",
        nextStep: "Shape repair flow",
      },
      {
        id: "w2",
        step: 2,
        mode: "Shape repair flow",
        bot: "Tinker",
        assignment: "Sketch 5-step flow + data model.",
        status: "Blocked",
      },
    ],
    artifacts: [],
    activity: [
      { id: "wv1", at: now(), bot: "Boss", action: "opened project", status: "Draft" },
      { id: "wv2", at: now(), bot: "Tinker", action: "blocked", status: "Blocked", blocker: "parts catalog credentials" },
    ],
  },
];