/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectCreatorRouteImport } from './routes/project-creator'
import { Route as OpenclawRouteImport } from './routes/openclaw'
import { Route as MasterLibraryRouteImport } from './routes/master-library'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ProjectCreatorRoute = ProjectCreatorRouteImport.update({
  id: '/project-creator',
  path: '/project-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenclawRoute = OpenclawRouteImport.update({
  id: '/openclaw',
  path: '/openclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLibraryRoute = MasterLibraryRouteImport.update({
  id: '/master-library',
  path: '/master-library',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/master-library': typeof MasterLibraryRoute
  '/openclaw': typeof OpenclawRoute
  '/project-creator': typeof ProjectCreatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/master-library': typeof MasterLibraryRoute
  '/openclaw': typeof OpenclawRoute
  '/project-creator': typeof ProjectCreatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/master-library': typeof MasterLibraryRoute
  '/openclaw': typeof OpenclawRoute
  '/project-creator': typeof ProjectCreatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/master-library'
    | '/openclaw'
    | '/project-creator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/master-library'
    | '/openclaw'
    | '/project-creator'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/master-library'
    | '/openclaw'
    | '/project-creator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  MasterLibraryRoute: typeof MasterLibraryRoute
  OpenclawRoute: typeof OpenclawRoute
  ProjectCreatorRoute: typeof ProjectCreatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project-creator': {
      id: '/project-creator'
      path: '/project-creator'
      fullPath: '/project-creator'
      preLoaderRoute: typeof ProjectCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openclaw': {
      id: '/openclaw'
      path: '/openclaw'
      fullPath: '/openclaw'
      preLoaderRoute: typeof OpenclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-library': {
      id: '/master-library'
      path: '/master-library'
      fullPath: '/master-library'
      preLoaderRoute: typeof MasterLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  MasterLibraryRoute: MasterLibraryRoute,
  OpenclawRoute: OpenclawRoute,
  ProjectCreatorRoute: ProjectCreatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
